In [30]:
print('In this hypothetical scenario, I have fake customer feedback data from a survey asking about customer satisfaction, product quality, and delivery experience from an e-commerce platform. I will perform a factor analysis to identify potential underlying factors that might drive customer satisfaction.')

In this hypothetical scenario, I have fake customer feedback data from a survey asking about customer satisfaction, product quality, and delivery experience from an e-commerce platform. I will perform a factor analysis to identify potential underlying factors that might drive customer satisfaction.


In [5]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r'customer_feedback.csv')


In [4]:
df.head()

Overall_Satisfaction  Product_Quality  Delivery_Speed  Customer_Service  \
0                     7                1              10                 8   
1                     4                8               6                 9   
2                     8                4               7                 6   
3                     5                4               9                 5   
4                     7                5               1                 6   

   Returns_Process  Price_Value  
0                2            4  
1                5            3  
2                2           10  
3                2            5  
4                6            5

In [8]:
#pip install factor-analyzer

In [9]:
from factor_analyzer import FactorAnalyzer
from sklearn.preprocessing import StandardScaler

In [10]:
# Select the variables for factor analysis
variables_for_fa = [
    'Overall_Satisfaction', 'Product_Quality', 'Delivery_Speed',
    'Customer_Service', 'Returns_Process', 'Price_Value'
]

In [11]:
# Extracing the selected variables
selected_data = df[variables_for_fa]

In [12]:
# Standardizing the data for factor analysis
scaler = StandardScaler()
scaled_data = scaler.fit_transform(selected_data)

In [13]:
# Creating a FactorAnalyzer object and specifying the number of factors
n_factors = 3 
fa = FactorAnalyzer(n_factors, rotation='varimax')

In [14]:
# Fitting the factor analysis model to the data
fa.fit(scaled_data)

FactorAnalyzer(rotation='varimax', rotation_kwargs={})

In [23]:
# Factor loadings
loadings = fa.loadings_
print("\nFactor Loadings:\n", loadings)


Factor Loadings:
 [[ 7.04414661e-03  2.61252858e-01  9.67059064e-04]
 [-9.25633539e-03  9.42280873e-03 -1.33695302e-01]
 [-4.20192950e-02 -1.05646221e-02  1.88867049e-01]
 [ 1.84343495e-02 -1.77090831e-01  1.16597750e-02]
 [ 6.29518087e-02  6.79266923e-02 -3.16082935e-02]
 [ 9.92828316e-01 -9.34849859e-02 -2.38039498e-02]]


In [22]:
print("\nInterpretation of Loadings:\n"
      "The first factor seems to represent aspects related to overall customer experience, including a strong association with satisfaction, perceived product quality, and perceived value for the price paid. "
      "Factor 2 might capture aspects related to the quality of customer service, but it's not as strongly represented as Factor 1 in this dataset. "
      "Factor 3, with Returns_Process having a moderate loading, might represent aspects related to the returns process or after the purchase experience, but it's not as prominent as the other factors.")


Interpretation of Loadings:
The first factor seems to represent aspects related to overall customer experience, including a strong association with satisfaction, perceived product quality, and perceived value for the price paid. Factor 2 might capture aspects related to the quality of customer service, but it's not as strongly represented as Factor 1 in this dataset. Factor 3, with Returns_Process having a moderate loading, might represent aspects related to the returns process or after the purchase experience, but it's not as prominent as the other factors.


In [28]:
# Variance explained by each factor
variance_explained = fa.get_factor_variance()
print(variance_explained)

(array([0.99191174, 0.1131681 , 0.05524779]), array([0.16531862, 0.01886135, 0.00920797]), array([0.16531862, 0.18417997, 0.19338794]))


In [29]:
print("\nInterpretation of Variance:\n"
      "Factor 1 explains most of the variability in how customers give feedback (almost 99%). This suggests that how satisfied they are overall, with product quality, and the value they perceive is the most crucial aspect of their feedback. Variables strongly connected to Factor 1 (customer satisfaction, product quality, percieved value) are the most crucial aspects of customer feedback in this dataset. These are the factors that the E-commerce company should focus their efforts on addressing.")


Interpretation of Variance:
Factor 1 explains most of the variability in how customers give feedback (almost 99%). This suggests that how satisfied they are overall, with product quality, and the value they perceive is the most crucial aspect of their feedback. Variables strongly connected to Factor 1 (customer satisfaction, product quality, percieved value) are the most crucial aspects of customer feedback in this dataset. These are the factors that the E-commerce company should focus their efforts on addressing.
